name: swift_conquer_game
description: RTS prototype powered by Swift Conquer Engine
version: 0.0.1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0
  swift_conquer_engine:
    git:
      url: https://github.com/Sinhuej/swift_conquer_engine.git

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sfx/
    - assets/fonts/
